# Generated by Django 5.0.6 on 2024-06-04 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 4, 19, 7, 29, 887143, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
