# Generated by Django 5.0.6 on 2024-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contact_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, upload_to="contact/pictures/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="contact",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
